Repository coala/corobo, pull requests merged in 2018-08, with the labels that each got.

#598 GitStats: Remove LabHub inheritance
  plugins/git_stats.plug
  plugins/git_stats.py
  tests/corobo_test_case.py
  tests/git_stats_test.py
Labels: bug, difficulty/medium, importance/medium, size/XS

#604 plugins/coatils.py: Remove __init__ constructor
  plugins/coatils.py
Labels: difficulty/newcomer, importance/medium, size/XS

#606 nevermind.py: Change regex pattern
  plugins/nevermind.py
  tests/nevermind_test.py
Labels: bug, difficulty/low, size/XS

#608 LabHubTestCase: LabHub testing setup
  tests/git_stats_test.py
  tests/labhub_test.py
  tests/labhub_test_case.py
Labels: area/tests, bug, process/approved, size/S

#612 test-requirements.txt: Sync
  test-requirements.txt
Labels: process/pending review, size/XS

#618 removed comment in webservices.raml regarding gitlab.com/coala/landin…
  webservices.raml
Labels: difficulty/newcomer, process/pending review, size/XS
