Repository coala/corobo, pull requests merged in 2018-05, with the labels that each got.

#508 Fix create new issue test
  tests/labhub_test.py
Labels: size/XS

#522 Adding ISSUE_TEMPLATE.md
  ISSUE_TEMPLATE.md
Labels: difficulty/newcomer, process/approved, size/XS

#525 .travis.yml: Disables notifications on success
  .travis.yml
Labels: area/ci, difficulty/newcomer, importance/low, process/pending review, size/XS

#523 .travis.yml: Enable travis-buddy
  .travis.yml
Labels: process/pending review, size/XS

#500 Rename COBOT_ROOT to BOT_ROOT
  Dockerfile
  README.md
  config.py
  utils/utils.py
Labels: area/config, importance/low, size/XS
