Repository coala/corobo, pull requests merged in 2018-10, with the labels that each got.

#624 Added Stack Overflow tag
  plugins/templates/lmgtfy.jinja2.md
Labels: difficulty/newcomer, process/approved, size/XS, type/markdown

#628 ci: Add repository check to semaphore scripts
  .ci/semaphore.docker.sh
Labels: difficulty/low, importance/medium, process/pending review, size/XS

#631 README.md: Update BOT_ADMINS description
  README.md
Labels: area/config, difficulty/newcomer, documentation, initiatives/gci, process/approved, size/XS, type/markdown

#634 config.py: Update default channel list
  config.py
Labels: area/config, difficulty/low, initiatives/gci, process/approved, size/XS

#637 searchdocs_test: change http links to https
  plugins/constants.py
  tests/searchdocs_test.py
Labels: area/tests, difficulty/newcomer, process/approved, size/XS

#639 Added 'Zulip' as option for ROOMS_TO_JOIN
  config.py
Labels: area/config, backend/zulip, difficulty/low, initiatives/gci, process/approved, size/XS

#641 config.py: Blacklist from-somewhere-else user
  config.py
Labels: difficulty/low, initiatives/gci, process/approved, size/XS
