Repository coala/corobo, pull requests merged in 2018-06, with the labels that each got.

#545 [GSoC '18]: requirements.txt: Bump IGitt version
  requirements.txt
Labels: area/ci, bug, enhancement, size/XS

#537 [GSoC '18] labhub: Modify invite permissions
  plugins/labhub.py
  plugins/templates/labhub/errors/not-eligible-invite.jinja2.md
  plugins/templates/labhub/errors/not-maintainer.jinja2.md
  tests/labhub_test.py
Labels: area/labhub, size/S

#489 plugins: Add SpammingAlert plugin
  plugins/constants.py
  plugins/spam.plug
  plugins/spam.py
  plugins/templates/spam_alert.jinja2.md
  tests/spam_test.py
Labels: difficulty/low, plugin proposal, process/approved, size/S

#541 [GSoC '18] labhub: assign_cmd newcomer's issue tracker
  plugins/labhub.py
  plugins/templates/labhub/errors/not-eligible.jinja2.md
  tests/labhub_test.py
Labels: enhancement, process/approved, size/XS

#539 [GSoC '18] labhub: Remove `Hello World` callback
  plugins/labhub.py
  plugins/templates/labhub/hello-world.jinja2.md
  tests/labhub_test.py
Labels: bug, enhancement, process/approved, size/XS

#530 Remove unnecessary self handling of TestBot
  tests/answer_test.py
  tests/coatils_test.py
  tests/wolfram_alpha_test.py
Labels: area/tests, difficulty/low, process/approved, size/S

#553 labhub: Add ban command
  plugins/ban.plug
  plugins/ban.py
  tests/ban_test.py
Labels: area/ci, bug, enhancement, size/S

#503 labhub.py: Block gci issue assignment
  plugins/labhub.py
  plugins/templates/labhub/errors/not-eligible.jinja2.md
  tests/labhub_test.py
Labels: area/labhub, difficulty/medium, process/approved, size/XS

#566 .gitignore: Add .pytest_cache
  .gitignore
Labels: enhancement, size/XS

#563 labhub.py: Remove unused variable
  plugins/labhub.py
Labels: difficulty/newcomer, process/approved, size/XS

#570 labhub_test: Increase timeout to fix random CI failures
  tests/labhub_test.py
Labels: bug, importance/critical, process/approved, size/XS

#576 LabHub: Remove redundant teams list
  plugins/labhub.py
  tests/labhub_test.py
Labels: enhancement, size/XS
